### ISSUE TITLE
seqFISH dropbox folder not available

### ISSUE THREAD

**Issue by drighelli** [BIRSBiointegration/Hackathon#12]
Hi,

I noticed that the link to the [dropbox folder](https://www.dropbox.com/sh/avj4nrd4la5i88u/AACafWwBbE-xsLvOGDwRZDpYa?dl=0) with the seqFISH data is not available anymore...
Is there any other link?

Thanks!

**Comment by aljabadi** [comment]
I think it's best to make sure that the data are packages up soon and hosted on Bioconductor so that issues such as this would not occur.

**Comment by drighelli** [comment]
Hi Al, @aljabadi 

indeed the dataset has been loaded in the SingleCellMultiModal package, but we need the place where we downloaded the dataset to cite it in the package and in the paper... 

Also, the dropbox folder contained the data preprocessing steps that would be good to briefly describe somewhere.

**Comment by mixOmicsTeam** [comment]
Hi Dario,
The updated link for upload is now: https://cloudstor.aarnet.edu.au/plus/s/ZuBIXuzuvc9JMj3
Regards,
Kim-Anh
--
A/Prof. Kim-Anh Lê Cao
NHMRC Career Development Fellow
School of Mathematics and Statistics, Melbourne Integrative Genomics Bld 184 | The University of Melbourne
T: +61 (0)3834 43971 | http://mixomics.org ***@***.***Omics_team | http://lecao-lab.science.unimelb.edu.au/



On 30 Apr 2021, at 17:32, dario righelli ***@***.******@***.***>> wrote:



Hi Al, @aljabadi<https://github.com/aljabadi>

indeed the dataset has been loaded in the SingleCellMultiModal package, but we need the place where we downloaded the dataset to cite it in the package and in the paper...

Also, the dropbox folder contained the data preprocessing steps that would be good to briefly describe somewhere.

**Comment by aljabadi** [comment]
Hi Dario @drighelli,

That makes sense. Please do let me know once the data are available via the SCMM package so we can update the vignettes.

**Comment by drighelli** [comment]
Hi Kim-Anh @mixOmicsTeam,

thanks for the link! 

@aljabadi it is already available see the vignette [here](https://bioconductor.org/packages/release/data/experiment/html/SingleCellMultiModal.html)

Best,
Dario

p.s. you can find also the scNMT data from this workshop available in the same package.
